### ISSUE TITLE
error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’

### ISSUE THREAD

**Issue by jackros1022** [TuZZiX/pcl_recognition#1]
hello,TuZZiX!
It is  amazing quiestion. I would greatly appreciate your help.

/home/jack/ros/view_ws/src/pcl_recognition/src/correspondence_grouping.cpp: In function ‘int main(int, char**)’:
/home/jack/ros/view_ws/src/pcl_recognition/src/correspondence_grouping.cpp:242:20: **error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’
   uniform_sampling.compute(keypointIndices1);**
                    ^
/home/jack/ros/view_ws/src/pcl_recognition/src/correspondence_grouping.cpp:251:20: **error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’
   uniform_sampling.compute(keypointIndices2);**
                    ^
/home/jack/ros/view_ws/src/pcl_recognition/src/object_recognizer.cpp: In member function ‘bool object_recognizer::recognize(std::vector<Eigen::Matrix<float, 3, 3> >&, std::vector<Eigen::Matrix<float, 3, 1> >&)’:
/home/jack/ros/view_ws/src/pcl_recognition/src/object_recognizer.cpp:110:26: error: ‘class pcl::UniformSampling<pcl::PointXYZRGB>’ has no member named ‘compute’
         uniform_sampling.compute( keypointIndices1 );
                          ^
/home/jack/ros/view_ws/src/pcl_recognition/src/object_recognizer.cpp:119:26: error: ‘class pcl::UniformSampling<pcl::PointXYZRGB>’ has no member named ‘compute’
         uniform_sampling.compute( keypointIndices2 );
                          ^
/home/jack/ros/view_ws/src/pcl_recognition/src/global_hypothesis_verification.cpp: In function ‘int main(int, char**)’:
/home/jack/ros/view_ws/src/pcl_recognition/src/global_hypothesis_verification.cpp:276:20: error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’
   uniform_sampling.compute(keypointIndices1);
                    ^
/home/jack/ros/view_ws/src/pcl_recognition/src/global_hypothesis_verification.cpp:285:20: error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’
   uniform_sampling.compute(keypointIndices2);
                    ^
make[2]: *** [pcl_recognition/CMakeFiles/correspondence_grouping.dir/src/correspondence_grouping.cpp.o] Error 1
make[1]: *** [pcl_recognition/CMakeFiles/correspondence_grouping.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [pcl_recognition/CMakeFiles/object_recognizer.dir/src/object_recognizer.cpp.o] Error 1
make[1]: *** [pcl_recognition/CMakeFiles/object_recognizer.dir/all] Error 2
make[2]: *** [pcl_recognition/CMakeFiles/global_hypothesis_verification.dir/src/global_hypothesis_verification.cpp.o] Error 1

**Comment by TuZZiX** [comment]
之前是因为一个编译问题改用了另外一种方法，你可以试试把：
pcl_recognition/src/correspondence_grouping.cpp的237到253注释掉然后把224到235行注释回来
pcl_recognition/src/global_hypothesis_verification.cpp的271到287注释掉然后把259到270行注释回来
并将pcl_recognition/src/object_recognizer.cpp的的105到121行替换为类似上面两个你取消注释的内容的形式
然后再编译试试~

**Comment by jackros1022** [comment]
@TuZZiX Thanks！

哈哈！谢谢你，问题解决了。

**Comment by nizqsut** [comment]
> @TuZZiX Thanks！
> 
> 哈哈！谢谢你，问题解决了。
同样的问题，怎样解决的？

**Comment by wafiq16** [comment]
can you write at latin letters? i cant read it. thanks before.
